site_name: dbMover
site_url: http://dbmover.monomelodies.nl/dbmover/docs/
repo_url: https://github.com/dbmover/dbmover

pages:
- Home:
    - 'General documentation': 'index.md'
- Plugins:
    - 'Conditionals': 'conditionals.md'
    - 'Data': 'data.md'
    - 'Force named indexes': 'force-named-indexes.md'
    - 'Indexes and constraints': 'indexes-and-constraints.md'
    - 'Functions and procedures': 'procedures.md'
    - 'Tables': 'tables.md'
    - 'Views': 'views.md'
